# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dsoGML
                                 A QGIS plugin
 DSO GML
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-06
        copyright            : (C) 2020 by Kasper Lingbeek
        email                : k.lingbeek@atos.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load dsoGML class from file dsoGML.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dso_gml import dsoGML
    return dsoGML(iface)
